# Generated by Django 3.1.7 on 2021-03-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=200)),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
